### ISSUE TITLE
Installing PMP on Debian Jessie

### ISSUE THREAD

**Issue by q3420094** [plexinc/plex-media-player#568]
Hi!

Following  the instructions on https://github.com/plexinc/plex-media-player#install-conan-dependency-fetcher, I can run the installation until it comes to unstall conan. Running the command "conan remote add plex https://conan.plex.tv" I get the following error: 

xxxxxx@yyyyy:~/pmp/mpv-build$ conan remote add plex https://conan.plex.tv
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'isort>=4.2.5' distribution was not found and is required by pylint

Can anybody help?

Wolfgang

**Comment by LongChair** [comment]
Did you end up fixing your build issue ?
Build system shouldn’t use conan anymore now.

**Comment by q3420094** [comment]
Hi!
In the meantime I've moved from Debian to Arch Linux. After installing Arch, everything is working fine and I'm enjoying PMP.
