### ISSUE TITLE
Windows Player: Photo Information crashes playback for geo-tagged photos

### ISSUE THREAD

**Issue by beatit99** [plexinc/plex-media-player#790]
### Test environment
PMS Version: 1.13.8.5395*
PMP Version: 3.71.1
Platform (Windows)

### Steps to reproduce
1. Photo Library, some with geotagging, some without
2. Browse to photo with Geotagging information, view (play) photo
3. Press Information Button to bring up information tab

### Current behavior
1. Error message - Playback Error: There was an unexpected error during playback. Please visit our forums if you continue to experience problems

### Expected behavior
1. Should get the side information bar showing photo properties, tags and small map
 - This feature works on web player
 - Information bar works for non-geotagged photos

Following error in player log:
2018-10-19 09:53:37 [ INFO  ] JS: TypeError: Cannot read property 'resize' of undefined 
2018-10-19 09:53:37 [ INFO  ] JS: %cTypeError: Cannot read property 'resize' of undefined
    at e.resize (https://api.tiles.mapbox.com/mapbox-gl-js/v0.42.2/mapbox-gl.js:484:4106)
    at new e (https://api.tiles.mapbox.com/mapbox-gl-js/v0.42.2/mapbox-gl.js:484:3029)
    at n._addMap (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/main-1-78760dedd297435a4319-plex-3.71.1-757f795.js:5631:12)
    at n.componentDidMount (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/main-1-78760dedd297435a4319-plex-3.71.1-757f795.js:5629:326)
    at dr (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/vendors-2-c84602644e336d5c4c3e-plex-3.71.1-757f795.js:374:3)
    at fr (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/vendors-2-c84602644e336d5c4c3e-plex-3.71.1-757f795.js:366:470)
    at ur (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/vendors-2-c84602644e336d5c4c3e-plex-3.71.1-757f795.js:365:422)
    at sr (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/vendors-2-c84602644e336d5c4c3e-plex-3.71.1-757f795.js:365:248)
    at interactiveUpdates (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/vendors-2-c84602644e336d5c4c3e-plex-3.71.1-757f795.js:435:125)
    at Be (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/vendors-2-c84602644e336d5c4c3e-plex-3.71.1-757f795.js:275:341)
    at HTMLDocument.n (file:///C:/Program%20Files/Plex/Plex%20Media%20Player/web-client/desktop/js/main-1-78760dedd297435a4319-plex-3.71.1-757f795.js:7454:328)

**Comment by mseeley** [comment]
Thank you @beatit99, we'll knock this out.

**Comment by mseeley** [comment]
Hi @beatit99 I've had to disable the map. It relies on WebGL which is currently unavailable in Plex Media Player. The fix is in review now in our user-interface repository. Once this issue closes it'll be up to a couple weeks until this fix will be included in a release.

**Comment by beatit99** [comment]
Thanks Matt. Hopefully a maps feature can be added back in the future.
